apiVersion: v1 # Versionen av Kubernetes API
kind: Service # Typen av Kubernetes-objekt; en tjänst (Service)
metadata: # Metadata om objektet
  name: nginx-service # Namnet på tjänsten; används för att identifiera tjänsten i kommandon och inom klustret
spec: # Specifikation av önskat beteende för denna tjänst
  selector: # Definierar hur tjänsten hittar vilka Pods som trafiken ska riktas till
    app: nginx # Väljer alla Pods med en etikett som har nyckeln "app" med värdet "nginx"
  ports: # Listan med portar på vilka tjänsten lyssnar och vidarebefordrar trafik
    - protocol: TCP # Nätverksprotokollet som denna port lyssnar på; i detta fall, TCP
      port: 80 # Porten på vilken tjänsten är exponerad inom klustret
      targetPort: 80 # Porten på Poden som trafiken ska riktas till
  type: NodePort # Anger typen av tjänst; NodePort innebär att den kommer att vara tillgänglig på varje nodens IP-adress med en statisk port inom området 30000-32767
