apiVersion: v1 # Versionen av Kubernetes API för tjänster
kind: Service # Typen av Kubernetes-objekt; en tjänst (Service)
metadata: # Metadata om objektet
  name: nginx-deployment-service # Namnet på tjänsten
spec: # Specifikation av önskat beteende för denna tjänst
  selector: # Definierar hur tjänsten hittar vilka Pods som trafiken ska riktas till
    app: nginx # Väljer alla Pods med en etikett som har nyckeln "app" med värdet "nginx"
  ports: # Listan med portar på vilka tjänsten lyssnar och vidarebefordrar trafik
    - protocol: TCP # Nätverksprotokollet som denna port lyssnar på
      port: 80 # Porten på vilken tjänsten är exponerad inom klustret
      targetPort: 80 # Porten på Poden som trafiken ska riktas till
  type: NodePort # Anger typen av tjänst; exponerar tjänsten på varje nods IP-adress
