apiVersion: v1 # Versionen av Kubernetes API
kind: ConfigMap # Typen av Kubernetes-objekt; en ConfigMap
metadata:
  name: app-config # Namnet på ConfigMap
data:
  MongoDbSettings__ConnectionString: "mongodb://mongodb-service:27017" # Anslutningssträng till MongoDB
  MongoDbSettings__DatabaseName: "ToDoAppDb" # Namn på MongoDB-databasen
  MongoDbSettings__CollectionName: "ToDoItems" # Namn på MongoDB-samlingen
  TODO_SERVICE_IMPLEMENTATION: MongoDb # Implementeringsinställning för tjänsten
