apiVersion: v1 # Versionen av Kubernetes API
kind: Service # Typen av Kubernetes-objekt; en tjänst (Service)
metadata:
  name: todo-service # Namnet på tjänsten
spec:
  selector:
    app: todo-webapp # Väljer Pods baserat på etikett "app" med värdet "todo-webapp"
  ports:
  - protocol: TCP # Nätverksprotokollet för denna port
    port: 80 # Porten som tjänsten är exponerad på
    targetPort: 80 # Porten på Pods dit trafiken ska riktas
  type: NodePort # Anger typen av tjänst; exponerar tjänsten på varje nods IP-adress
